### ISSUE TITLE
7DTD Loot Cleanup Modlet

### ISSUE THREAD

**Issue by Red51111** [Donovan522/donovan-7d2d-modlets#10]
Hi Donovan. I am using your Loot Cleanup mod. When bird nests are destroyed, they sound like a wooden box exploding. Would you mind updating the existing Loot Cleanup Modlet or creating a new one that would utilize a softer sound? 

I have tried myself to change the "sound_close" parameter but it does not appear to make any difference.  I am new to xml coding, so I assume my syntax is just not correct.

Thank you for your consideration.
Red5111

**Comment by dyoung522** [comment]
Great suggestion! I'll look into what's required to do this. Thanks!

**Comment by dyoung522** [comment]
Fixed, the latest version of LootCleanup has the default sound for bird nests changed to the plant harvesting sound.
