### ISSUE TITLE
Label LongerLootBags (and others as appropriate) as A19-compatible?

### ISSUE THREAD

**Issue by gadbot-rev2** [Donovan522/donovan-7d2d-modlets#11]
Folks on my server love your simple, focused modlets and have been using them steadily. However, none of them show up on the list of A19-compatible modlets. I've confirmed that at least one of them (LongerLootBags) should work just the same on A19 as A17-18. Would you be willing to update the compatibility tags for this and others which still work in A19? (If you want me to assist in testing any and all of them, I'd be willing to do so.)

Obviously, this isn't a game-breaking issue, since it's easy enough to manually install and use the mods, but my tech-phobic friends would benefit if they showed up in the mod launcher and 7daystodiemods.com.

**Comment by dyoung522** [comment]
I've just updated them all to A19 now that stable is out!

Enjoy!
