### ISSUE TITLE
Fog Mod. Make the fog 24/7?

### ISSUE THREAD

**Issue by JDubbedN** [Donovan522/donovan-7d2d-modlets#16]
Love your fog mod at night. Reminds me so much of Silent Hill. How can I make your fog mod show 24/7 instead of just at night? And am I able to modify the xml file in order to increase and decrease fog amount and the distance the fog is? I see your worldglobal.xml file and see the fog power value which is 1,0.40. Not sure what that indicates but maybe if I modify those values?

Thanks!

**Comment by dyoung522** [comment]
There are two values separated by a comma.

The first value is for the day, the second value is for the night.

The value itself is a number between 0 and 1... representing the % of visibility, with 1 being 100% visibility (i.e. no fog).

**Comment by dyoung522** [comment]
I won't make the change here, but you can modify the XML on your side to make that value whatever you desire. Find me on guppy's server, or leave a comment here if you have any further questions. Happy to help!
