### ISSUE TITLE
Issue loading on non windows system.  Case sensitive file name issue

### ISSUE THREAD

**Issue by ghost** [Donovan522/donovan-7d2d-modlets#17]
**Describe the bug**
Non windows systems are usually "case sensitive" in their file names, and it appears the game (on non-windows systems) requires the "modinfo.xml" file in your mod to be named "ModInfo.xml". This change should not break the mod on windows systems.  I 
renamed the file to ModInfo.xml and it worked

**To Reproduce**

1. Copy the mod in the "Mods" folder of the game
2. Start the game (continue/new, etc).  Hit "F1" to watch it load (console window appears)
3. Game will say "Trying to load from folder: donovan-nightfog" but will then say "Folder donovan-nightfog does not contain a ModInfo.xml, ignoring"
"Failed loading mod from folder: donovan-nightfog"
4. When game starts, the mod is not loaded.

**Expected behavior**
The mod loads without issues

**Screenshots**
![20200923201242_1](https://user-images.githubusercontent.com/46878184/94090044-3a3d1180-fdda-11ea-92d0-60b3853e38be.JPG)

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: Err...Steam?
- Version: 
7 Days to Die game: a19.1 b8.  
Your mod: Version "19.0.1.0"

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by dyoung522** [comment]
Yup, no problem. I'll get this fixed ASAP

**Comment by dyoung522** [comment]
All `ModInfo.xml` files should now be the proper case.
