### ISSUE TITLE
Craft Schematics - Table Saw Uncraftable/Disabled

### ISSUE THREAD

**Issue by Runzu87** [Donovan522/donovan-7d2d-modlets#18]
I've installed the mod and I can search up the recipes show up to craft schematics. However, I have nowhere to craft them. I spawned a table saw and tried to no avail. In A19.2 the table saw is no longer craftable nor a workstation. I checked the wiki and apparently it's currently a useless block now.

I do have a few other mods installed, but considering the update states the table saw has been disabled completely, I think that's the culprit.

**Comment by dyoung522** [comment]
I'll remove it from the mod.

**Comment by Runzu87** [comment]
Thank you! I wasn't sure if there'd be more to it or not. Will it no longer require a crafting station now?

**Comment by DreamSmith** [comment]
It may be worth adding a recipe to the workbench allowing crafting of the table saw.

**Comment by dyoung522** [comment]
Yeah, we can possibly add the tablesaw back into the game or just move the craftable schematics to use the workbench instead.

**Comment by dyoung522** [comment]
Fixed! Schematics are now crafted at the workbench instead.
