### ISSUE TITLE
loot bags still the same

### ISSUE THREAD

**Issue by bleckman74** [Donovan522/donovan-7d2d-modlets#19]
i spawned in  50 zombies, the backpacks were all the same rate. 1 out of 50, no change

**Comment by dyoung522** [comment]
I haven't had a chance to update the modlets to A19.2 yet, so I'll look into this.

**Comment by melvil6300** [comment]
We want the back to disappear more quickly. Is it possible to shorten the time by changing the XML value of "Longer Loot Bags-Mod"?

**Comment by dyoung522** [comment]
I was unable to replicate this bug. Might have been fixed in the latest update.
