### ISSUE TITLE
NullReferenceException - Small Trash Bin

### ISSUE THREAD

**Issue by Neil-Ph** [Donovan522/donovan-7d2d-modlets#23]
The issue:
The console window opens up and I see this in red:
NullReferenceException: Object reference not set to an instance of an object
in the console window.
This happens when I press E when trying to search the small trash bin. (The small white metal bin commonly found in a bathroom)

**To Reproduce**

1. Look at a small trash bin
2. Press E to search

**Expected behavior**
A normal loot window to open, like the ones when you press E to search other items for example a cupboard.

**Screenshots**
N/A ?

**Desktop (please complete the following information):**
N/A ?

**Smartphone (please complete the following information):**
N/A

**Additional context**
This may also apply to the large green plastic bin with visible trash bags that would normally be lootable.

Using Mod Launcher program. Overhaul mod Darkness Falls with additional mod Sorcery.
This mod added with mod launcher program as a modlet.

Might it be an issue with item ID's ?

**Comment by dyoung522** [comment]
Sadly, I haven't updated the mods for the latest versions of 7days yet, nor am I able to support mixing mods as it's highly likely that there will be conflicts.
