### ISSUE TITLE
Night Fog 7 Days to Die

### ISSUE THREAD

**Issue by Zyaku-Eketwi** [Donovan522/donovan-7d2d-modlets#24]
**Is your feature request related to a problem? Please describe.**
**_(no problem works fine)_**
**Describe the solution you'd like**
**_(Feel like the Fog is a bit too much in terms of volume also would it be possible to have the fog a little clearer kinda like a rolling mist . Still difficult to see thru but not as intense as it is now)_**
**Describe alternatives you've considered**
**_(What I stated above)_**
**Additional context**

**Comment by dyoung522** [comment]
Unfortunately, this isn't possible at this time.
