### ISSUE TITLE
Loot clean up

### ISSUE THREAD

**Issue by trollusk** [Donovan522/donovan-7d2d-modlets#25]
Is Loot Clean Up compatible with Undead Legacy? Not sure what I'm doing wrong, but I can't get it to work. I'm using alpha 19.6, latest Undead Legacy, and Loot Clean up all installed via mod launcher. I've tried renaming LCU to move it to last in the modlet load order but this had no effect.

**Comment by Foruxx** [comment]
I have the same problem I can't get the mod to run in undead legacy in any way I hope they fix it
