### ISSUE TITLE
Horde Night Only Fog

### ISSUE THREAD

**Issue by Rdelaura** [Donovan522/donovan-7d2d-modlets#27]
**Is your feature request related to a problem? Please describe.**
No Problem, just a request if possible

**Describe the solution you'd like**
Instead of fog every night, fog only on horde night

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by dyoung522** [comment]
I'll look into this, see if it's possible. Thanks for the suggestion, and sorry for the long delay in response.

**Comment by dyoung522** [comment]
The way the game files are laid out, this isn't feasible to do at this time. Sorry.
