### ISSUE TITLE
Better Buffs - Changes to Sprained debuff

### ISSUE THREAD

**Issue by xerberus333** [Donovan522/donovan-7d2d-modlets#31]
**Is your feature request related to a problem? Please describe.**
It's always bothered me that the sprained debuff didn't have more options to cure (other than the health bar candy, which applies to all debuffs anyway). Broken bones get splints and casts.

**Describe the solution you'd like**
Allow Splint and Medical Cast to be applied to the sprained debuff, similar to the broken bone debuff

**Describe alternatives you've considered**
n/a

**Additional context**
[Sprained Leg - Wiki](https://7daystodie.fandom.com/wiki/Sprained_Leg)
This wiki page implies a splint may be used. However, in practice, it doesn't work. Attempting to use a splint in the inventory with Sprain debuff in effect doesn't do anything. The splint isn't consumed, and the treated injury buff doesn't trigger. Same goes for medical cast.

**Comment by dyoung522** [comment]
Excellent idea, thanks!

**Comment by dyoung522** [comment]
This now has a fix in the vanilla game. The Physician Perk will now allow you to heal sprains.
