### ISSUE TITLE
Cooking issues after applying AIO

### ISSUE THREAD

**Issue by Jacerie** [Donovan522/donovan-7d2d-modlets#34]
After applying the AIO mod, three cooking recipes are not usable.
The required ingredients are in my inventory and all secondary parts are present.
The Raw Meat counter always reads 0 for Charred Meat, Grilled Meat, and Boiled Meat.
Raw Meat is usable in other recipes.

![A20 3_2022-03-16_04-16-50](https://user-images.githubusercontent.com/101705186/158580946-d116c253-e42c-467d-a43b-f0bdade17e64.jpg)
![A20 3_2022-03-16_04-16-53](https://user-images.githubusercontent.com/101705186/158580954-225e9d8b-6d4a-4dc0-b65f-e253e8d551cc.jpg)
![A20 3_2022-03-16_04-16-56](https://user-images.githubusercontent.com/101705186/158580967-8e4b37ad-1d18-4e25-af6a-4de75d49c7b5.jpg)

**Comment by dyoung522** [comment]
Yup, good catch. I believe you can still make the meals, but they are free (as in, they don't use resources). Whoops!

**Comment by dyoung522** [comment]
This has been fixed.
