### ISSUE TITLE
Cannot Use Cement Mixed, Forge or Chemistry Set

### ISSUE THREAD

**Issue by Steev93** [Donovan522/donovan-7d2d-modlets#38]
**Describe the bug**

**To Reproduce**

![image](https://user-images.githubusercontent.com/11894767/215462299-128c77c9-bdf9-4c4f-92c0-31bb9cf8fe6b.png)

**Desktop (please complete the following information):**

Server is hosted with Streamline Servers

**Additional context**

**Comment by dyoung522** [comment]
Fixed in latest release
