### ISSUE TITLE
Mega Backpack's extra slots aren't working properly

### ISSUE THREAD

**Issue by Makekel** [Donovan522/donovan-7d2d-modlets#48]
I've noticed that with the A21 version of Mega Backpack, if your vanilla inventory slots are full, you can't quick loot with R (default keybind) or shift click items from storage/loot into your inventory. You have to manually drag items into the new slots.

**Comment by Makekel** [comment]
UPDATE: After closing the game and reopening/loading my save file, all the items that were in the additional inventory slots were gone.

**Comment by II-NaStY-III** [comment]
I could never get it to work either and sounds like Im glad I deleted it went with the other with 96 slots lol

**Comment by dyoung522** [comment]
I haven't noticed this myself, but thanks for reporting it... I'll look into it.

By chance are you using any other mods which might modify the UI (except donovan-ui)?

**Comment by dyoung522** [comment]
> UPDATE: After closing the game and reopening/loading my save file, all the items that were in the additional inventory slots were gone.

if you uninstall the mod, you won't be able to see any items that were in those extra slots, but they're not gone... you just can't see them. Re-installing the mod should recover them. This will be true of any mod the modifies your backpack rows and columns.

**Comment by dyoung522** [comment]
I'm sorry, but I'm unable to replicate this issue locally. I've run several tests with only `megabackpack` installed and with `AiO`, and everything works as expected.

Please make sure you have the latest version of the mod installed which is, at the time of this writing, `v21.0.1`
