### ISSUE TITLE
Rename Modinfo.xml to ModInfo.xml

### ISSUE THREAD

**Issue by fesch89** [Donovan522/donovan-7d2d-modlets#5]
Rename Modinfo.xml to ModInfo.xml to have the modlets loaded ;)

**Comment by rpryor** [comment]
I literally just did the same thing on my server to finally get them to work. I believe this is necessary for Linux based servers as case sensitivity is critical.

**Comment by dyoung522** [comment]
Ah, okay... didn't realize that. Will do today!

**Comment by dyoung522** [comment]
Thanks for the feedback! I don't personally run 7d2d on a linux server, so if you see any other case sensitivity issues, please report them.
