### ISSUE TITLE
An idea

### ISSUE THREAD

**Issue by ycoskun41** [Donovan522/donovan-7d2d-modlets#52]
I want to add text or logo to any place I marked. Can you recommend a code snippet?

![image](https://github.com/DonovanMods/donovan-7d2d-modlets/assets/83180501/369764a0-2636-49f4-a9cd-61ae3348a5ef)

**Comment by dyoung522** [comment]
I'm sorry, but this is not the proper venue for this question. Please ask in the modding discord or other forums pertinent to this type of question.
