### ISSUE TITLE
[Better Collectors] Collectors dont update correctly

### ISSUE THREAD

**Issue by Joly0** [Donovan522/donovan-7d2d-modlets#55]
**Describe the bug**
The Collectors dont update correctly like they should do. When i empty a collector and leave the area and return after some while the collector "says" "Empty Dew Collector". After opening it, it shows no progress at all. When i close it the text changes to "(E) Search Dew Collector" and when i open it again, it shows the correct progress and i can take out my water.

**To Reproduce**
Place a dew collector
Leave the area
Come back after some time
Look and open dew collector

**Expected behavior**
The dew collector should update correctly and shouldnt need to be opened twice

**Screenshots**
![grafik](https://github.com/DonovanMods/donovan-7d2d-modlets/assets/13993216/618366fd-d3b3-462d-8103-1bc27afefefb)
![grafik](https://github.com/DonovanMods/donovan-7d2d-modlets/assets/13993216/cb01e8b3-8b72-4094-bcce-595f819bf91a)
![grafik](https://github.com/DonovanMods/donovan-7d2d-modlets/assets/13993216/c124dc74-42f9-4a61-ac0b-5d4cebec92f3)
![grafik](https://github.com/DonovanMods/donovan-7d2d-modlets/assets/13993216/20002007-c594-4c10-9c7a-a64b7d9f2800)

**Comment by Joly0** [comment]
Btw, would like to look into the source code, but couldnt find it? Maybe i could find the issue there (i have some experience in c#)

**Comment by kgiesing** [comment]
Just FYI, though I was not able to reproduce the issue myself, I believe it had to do with chunk observers being lost when exiting the game. I have a new version of Rain Collectors that I hope will mitigate the issue. Please give it a shot and let me know if things are better.
https://gitlab.com/karlgiesing/7d2d-a21-modlets/-/tree/main/khzmusik_Rain_Collector

**Comment by dyoung522** [comment]
> Just FYI, though I was not able to reproduce the issue myself, I believe it had to do with chunk observers being lost when exiting the game. I have a new version of Rain Collectors that I hope will mitigate the issue. Please give it a shot and let me know if things are better. https://gitlab.com/karlgiesing/7d2d-a21-modlets/-/tree/main/khzmusik_Rain_Collector

Awesome, I'll get the new DLL installed here too, thanks!

**Comment by dyoung522** [comment]
Updated in https://github.com/DonovanMods/donovan-7d2d-modlets/releases/tag/A21.0.5

**Comment by marnason** [comment]
I'm still experiencing this issue on A21.0.5.
