### ISSUE TITLE
Mega Backpack:Inventory slots not working

### ISSUE THREAD

**Issue by saiakesani** [Donovan522/donovan-7d2d-modlets#61]
So im running the current mods

War3zuk-7DTD-Stable-ModLets-2022-main-War3zuk 50k Stacks
donovan-ui
donovan-megabackpack

the inventory still shows up as the default inventory, i checked the 7days2diemods.com listing for further instructions, checked the README and even inspected the other files in the mod its self with out editing anything, but any way i try i cant find a way to get the mod working, is there a dependency?

**Comment by dyoung522** [comment]
I'll look into this, but locally it works as expected. Are any other mods installed beyond the 50k stacks? I'm not familiar with that mod, but there could be conflicts with it and megabackpack.
