### ISSUE TITLE
LessGrind Modlet - resourceIronFragment for terrOreIron/oreIronBoulder

### ISSUE THREAD

**Issue by FunkyBigdog** [Donovan522/donovan-7d2d-modlets#9]
For me there was a issue with the xpath regarding the lessgrind modlet.  This was due to the terrOreIron and oreIronBoulder paths drop event pointing to resourceIronFragment which for me isn't in the main blocks.xml anymore.  It seems they replaced it with resourceScrapIron variable.

I am using the latest experimental build (At this time it is 18.1 b6).

**Comment by dyoung522** [comment]
I haven't updated the mods for the latest experimental build yet. They've changed some of the resource names in the latest experimental, which would break stable.

I'll create a new branch to fix changes in experimental soon.

**Comment by dyoung522** [comment]
Fixed in `experimental` branch.

**Comment by dyoung522** [comment]
Moved to `stable` branch since 18.1 b7 has gone stable.
